apiVersion: v1
kind: Service
metadata:
  name: model-service-postgres
  labels:
    app: model-service
spec:
  ports:
    - port: 5432
  selector:
    app: model-service
    tier: postgres
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-service-postgres-deployment
  labels:
    app: model-service
spec:
  selector:
    matchLabels:
      app: model-service
      tier: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: model-service
        tier: postgres
    spec:
      containers:
      - image: postgres
        name: postgres
        ports:
        - containerPort: 5432 
          name: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-service-server-deployment
  labels:
    app: model-service-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-service-server
  template:
    metadata:
      labels:
        app: model-service-server
    spec:
      containers:
      - name: model-service-server
        image: pieterpa/model-service
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8053
        resources:
          limits:
            cpu: 0.2
            memory: "200Mi"
        env:
        - name: POSTGRES_HOST
          value: "model-service-postgres"
        - name: POSTGRES_PORT
          value: "5432"
---
apiVersion: v1
kind: Service
metadata:                     
  name: model-service-server
  labels:
    app: model-service-server
spec:                         
  type: NodePort
  selector:
    app: model-service-server
  ports:
  - name: http
    port: 8053
    targetPort: 8053