apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-model
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: modeldata
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: testgresql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-service-server-deployment
  labels:
    app: model-service-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-service-server
  template:
    metadata:
      labels:
        app: model-service-server
    spec:
      containers:
      - name: model-service-server
        image: pieterpa/model-service
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8053
        resources:
          limits:
            cpu: 0.2
            memory: "200Mi"
        env:
        - name: POSTGRES_HOST
          value: "model-service-postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "modeldata"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "testgresql"
---
apiVersion: v1
kind: Service
metadata:                     
  name: model-service-server
  labels:
    app: model-service-server
spec:                         
  type: NodePort
  selector:
    app: model-service-server
  ports:
  - name: http
    port: 8053
    targetPort: 8053
---
apiVersion: v1
kind: Service
metadata:                     
  name: postgres-service
  labels:
    app: postgres-service
spec:                         
  type: NodePort
  selector:
    app: postgres-service
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432